USE FABRICA 
GO

CREATE TABLE TIPOS_DE_PRODUCTOS
(
ID_TIPOS TINYINT  NOT NULL PRIMARY KEY IDENTITY(1,1),
DESCRIPCION VARCHAR(100) NOT NULL,
SEÑA SMALLMONEY NULL 
)


CREATE TABLE MATERIALES
(
 ID_MATERIAL TINYINT NOT NULL PRIMARY KEY IDENTITY(1,1),
 NOMBRE VARCHAR(50) NOT NULL 


)


CREATE TABLE TIPOS_DE_TAREAS
(	ID_TAREA TINYINT NOT NULL PRIMARY KEY IDENTITY(1,1),
	DESCRIPCIO VARCHAR(50) NOT NULL 


)

ALTER TABLE PRODUCTOS ADD CATEGORIA  TINYINT NOT NULL
 FOREIGN KEY REFERENCES TIPOS_DE_PRODUCTOS(ID_TIPOS)
 
 ALTER TABLE PRODUCTOS 
 ADD MATERIAL TINYINT NOT NULL FOREIGN KEY REFERENCES MATERIALES(ID_MATERIAL)



 CREATE TABLE PRODUCTO_COLABORADOR_TAREA
 (	PRODUCTO INT NOT NULL FOREIGN KEY REFERENCES PRODUCTOS(ID),
	COLABORADOR INT NOT NULL FOREIGN KEY REFERENCES COLABORADORES(LEGAJO),
	ACCION TINYINT NOT NULL FOREIGN KEY REFERENCES TIPOS_DE_TAREAS(ID_TAREA)

 )



 ALTER TABLE PRODUCTO_CLABORADOR_TAREA ADD CONSTRAINT PK_PCT 
 PRIMARY KEY (PRODUCTO,COLABORADOR,ACCION)