CREATE DATABASE MINIUM

GO


USE  MINIUM

GO


CREATE TABLE ALUMNOS
(
	LEGAJO INT NOT NULL PRIMARY KEY,
	APELLIDO VARCHAR(50) NOT NULL, 
	NOMBRE VARCHAR(50) NOT NULL,


)

CREATE TABLE CARRERAS
(	
	ID_CAR TINYINT NOT NULL PRIMARY KEY IDENTITY(1,1),
	NOMBRE VARCHAR(50) NOT NULL UNIQUE(NOMBRE),
	


)

CREATE TABLE MATERIAS
(	ID_MAT SMALLINT NOT NULL PRIMARY KEY IDENTITY(1,1),
	NOMBRE VARCHAR(50) NOT NULL UNIQUE(NOMBRE),
	CARRERA TINYINT NOT NULL FOREIGN KEY REFERENCES CARRERAS(ID_CAR)

)

GO
CREATE TABLE INSCRIPCIONES
(	LEGAJO INT NOT NULL FOREIGN KEY REFERENCES ALUMNOS(LEGAJO),
	MATERIA SMALLINT NOT NULL FOREIGN KEY REFERENCES MATERIAS(ID_MAT),
	ANIO SMALLINT NOT NULL,
	ESTADO CHAR NOT NULL CHECK(ESTADO IN('L','A')),
	PRIMARY KEY(LEGAJO,MATERIA,ANIO)


)

GO