USE TP_NORMALIZACION_N1_2019
GO
INSERT INTO PROVINCIAS (NOMBRE) VALUES('Buenos Aires')
INSERT INTO PROVINCIAS (NOMBRE) VALUES('Catamarca')
INSERT INTO PROVINCIAS (NOMBRE) VALUES('Chaco')
INSERT INTO PROVINCIAS (NOMBRE) VALUES('Chubut')
INSERT INTO PROVINCIAS (NOMBRE) VALUES('Córdoba')
INSERT INTO PROVINCIAS (NOMBRE) VALUES('Corrientes')
INSERT INTO PROVINCIAS (NOMBRE) VALUES('Entre Ríos')
INSERT INTO PROVINCIAS (NOMBRE) VALUES('Formosa')
INSERT INTO PROVINCIAS (NOMBRE) VALUES('Jujuy')
INSERT INTO PROVINCIAS (NOMBRE) VALUES('La Pampa')
INSERT INTO PROVINCIAS (NOMBRE) VALUES('La Rioja')
INSERT INTO PROVINCIAS (NOMBRE) VALUES('Mendoza')
INSERT INTO PROVINCIAS (NOMBRE) VALUES('Misiones')
INSERT INTO PROVINCIAS (NOMBRE) VALUES('Neuquén')
INSERT INTO PROVINCIAS (NOMBRE) VALUES('Río Negro')
INSERT INTO PROVINCIAS (NOMBRE) VALUES('Salta')
INSERT INTO PROVINCIAS (NOMBRE) VALUES('San Juan')
INSERT INTO PROVINCIAS (NOMBRE) VALUES('Santa Cruz')
INSERT INTO PROVINCIAS (NOMBRE) VALUES('Santiago del Estero')
INSERT INTO PROVINCIAS (NOMBRE) VALUES('Tierra del Fuego')
INSERT INTO PROVINCIAS (NOMBRE) VALUES('Tucumán')
-------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------





